# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8aaf98e04871cbe47d3f5395aed378cba3226d541875ae1ec8b5f17851eec9b0c95cacb5a24751da43f40dec284171f284c375cb57042826e434e21e65ea43af

test:
  secret_key_base: 5c8c3197d5da9e5d8ae8f780f7f8b603d1d221758e8582fedcc3bf4616c211cf346e25a357d42a2d3d8f33311d39f7d6f3015ff5b27dbac20a027bd48da9a0fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
